### ISSUE TITLE
How to make images show up in html pages?

### ISSUE THREAD

**Issue by maxott** [talsma-ict/umldoclet#111]
This is most likely a very stupid question, but I'm trying for the last few hours to make this work. I see that all the puml and image files are being created, but they aren't showing up in the html pages. 

I even cloned this repo and built it (`develop-v1` as I'm still stuck on java8) and same result. Everything is created but no link/reference in the respective HTML pages.

What am I missing here?

Thanks

**Comment by sjoerdtalsma** [comment]
This is not automatically available for `v1`... yet?

Good news: it _is already_ implemented for `v2` and shouldn't be that hard to port back to `v1`.

[Issue 61 mentions a temporary workaround:](https://github.com/talsma-ict/umldoclet/issues/61#issuecomment-365681302)
> For the moment, you can include the image by adding a regular HTML <img> tag in your JavaDoc. The URL can be relative to the html, or you can define an imagedir to be used.

**Comment by sjoerdtalsma** [comment]
I tagged this as both a _question_ and _improvement_ as this functionality is obviously valuable for `v1` as well!

Hopefully I can wrestle some time between my full time job and moving house :wink:

**Comment by sjoerdtalsma** [comment]
@maxott Thanks for bringing this up!

**Comment by maxott** [comment]
@sjoerdtalsma Thanks for the quick response. Is weird that there isn't a clean way to hook into the html generation phase.

**Comment by sjoerdtalsma** [comment]
@maxott Could you test with `v1.1.0` to verify that the diagrams are now automatically added to the generated HTML files?

**Comment by msche** [comment]
I used the latest version as available in MVN central but images were not showing up in javadoc.

**Comment by sjoerdtalsma** [comment]
>I used the latest version as available in MVN central but images were not showing up in javadoc.

That's unfortunate! Which version was that? Technically, the latest version is `2.0.0-rc.4` and requires Java 9.

**Comment by sjoerdtalsma** [comment]
@msche The javadoc for `1.1.0` version of this doclet itself:
- [1.1.0 javadoc of 'rendering' package](https://static.javadoc.io/nl.talsmasoftware/umldoclet/1.1.0/nl/talsmasoftware/umldoclet/rendering/package-summary.html)

**Comment by maxott** [comment]
I can validate that it works for the `umldoclet` repo on my machine. 

However, there are some CSS issues. See attached screenshot. Which makes me wonder on how I could control the type of diagram attached to a package page vs a class page.

Thanks for the quick turnaround. 

 <img width="992" alt="screenshot" src="https://user-images.githubusercontent.com/726959/46119417-1deb5600-c24e-11e8-8ab8-0500d14dfaf6.png">

**Comment by sjoerdtalsma** [comment]
@maxott Thank you for validating the fix, much appreciated!
> However, there are some CSS issues.

You are right, thank you for pointing this out. I have created a new [issue 118](https://github.com/talsma-ict/umldoclet/issues/118) for this.

> Which makes me wonder on how I could control the type of diagram attached to a package page vs a class page.

Not sure I quite follow your reasoning here. The doclet will add a package diagram to the corresponding package documentation and a class diagram to the corresponding class documentation. If this is not what you want, I'm curious to what you think it should be. However, I want to give it full focus without it getting lost in an issue about automatically included images. 
--> _Could you please create another issue where we can discuss how we can customize this behaviour in a way that better suits everybody's needs?_

**Comment by sjoerdtalsma** [comment]
Pinging @maxott @msche : I intend to close this issue in 24 hours if there are no further reactions.

Feel free to open new issues to follow-up on bugs or customisation of the automatically included diagrams however.

**Comment by sjoerdtalsma** [comment]
Closing, diagrams are generated and issue is getting stale. Feel free to reopen this or a new issue where appropriate
