### ISSUE TITLE
javadoc: error - Cannot find doclet class nl.talsmasoftware.umldoclet.UMLDoclet

### ISSUE THREAD

**Issue by royberris** [talsma-ict/umldoclet#215]
Hello,

I am not an advanced Gradle user but I am doing a school project where we need to build a Java application with Gradle. I also need to upload a weekly UML Class Diagram. Instead of making it myself I thought it would be a good idea to generate this from source code. I stumbled upon this "plugin". 

Could you help me with my configuration so I can generate this from source code?

`build.gradle`:

```
plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.8'
    id 'org.beryx.jlink' version '2.12.0'
}

apply plugin: 'java'

repositories {
    mavenCentral()
}

configurations {
    umlDoclet
}

dependencies {
    // https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
    compile group: 'org.apache.commons', name: 'commons-collections4', version: '4.4'
    // https://mvnrepository.com/artifact/mysql/mysql-connector-java
    compile group: 'mysql', name: 'mysql-connector-java', version: '8.0.18'
    // Used for generating UML class diagram
    umlDoclet "nl.talsmasoftware:umldoclet:2.0.6"
}

javafx {
    version = "13"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

javadoc {
    source = sourceSets.main.allJava
    options.docletpath = configurations.umlDoclet.files.asType(List)
    options.doclet = "nl.talsmasoftware.umldoclet.UMLDoclet"
}

mainClassName = "$moduleName/nl.avans.sagrada.MainApp"

jlink {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'Sagrada'
    }
}
```

So I synced the project which worked but whenever I run the `javadoc` command from Gradle it doesn't seem to work. I do get all the javadoc generated files but I don't see any UML diagrams. 

I have no experience with javadoc so the usage page is too little information for me to get started. 

Thanks in advance!

**Comment by sjoerdtalsma** [comment]
Hi, first of all thanks for using the UML Doclet.
Unfortunately I must admit that I do not use Gradle myself, but let's see if we can troubleshoot your issue.

Can you attach  a log of the output Gradle gives you to this issue?

**Comment by royberris** [comment]
Hi,

I am using IntelliJ and from the Gradle panel, I select the "javadoc" task. I am assuming this is the right one. So this runs fine but I don't see any images in the javadoc output directory.

Raw command is: `gradle javadoc --info`

Output from this one (with --info):

```
1:47:15 PM: Executing task 'javadoc --info'...

The client will now receive all logging from the daemon (pid: 218052). The daemon log file: C:\Users\roy\.gradle\daemon\4.10.3\daemon-218052.out.log
Starting 14th build in daemon [uptime: 1 hrs 20 mins 16.497 secs, performance: 100%, no major garbage collections]
Using 12 worker leases.
Starting Build
Settings evaluated using settings file 'D:\Avans\Blok 2\Sagrada-Core\settings.gradle'.
Projects loaded. Root project using build file 'D:\Avans\Blok 2\Sagrada-Core\build.gradle'.
Included projects: [root project 'Sagrada']

> Configure project :
Evaluating root project 'Sagrada' using build file 'D:\Avans\Blok 2\Sagrada-Core\build.gradle'.
Found module name 'Sagrada'
------------------------------------------------------------------------
Detecting the operating system and CPU architecture
------------------------------------------------------------------------
os.detected.name=windows
os.detected.arch=x86_64
os.detected.version=10.0
os.detected.version.major=10
os.detected.version.minor=0
os.detected.classifier=windows-x86_64
All projects evaluated.
Selected primary task 'javadoc' from project :
Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':javadoc']
:compileJava (Thread[Task worker for ':',5,main]) started.

> Task :compileJava
Task ':compileJava' is not up-to-date because:
  Output property 'destinationDir' file D:\Avans\Blok 2\Sagrada-Core\build\classes\java\main has been removed.
  Output property 'destinationDir' file D:\Avans\Blok 2\Sagrada-Core\build\classes\java\main\module-info.class has been removed.
  Output property 'destinationDir' file D:\Avans\Blok 2\Sagrada-Core\build\classes\java\main\nl has been removed.
All input files are considered out-of-date for incremental task ':compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Created classpath snapshot for incremental compilation in 0.003 secs. 1 duplicate classes found in classpath (see all with --debug).
:compileJava (Thread[Task worker for ':',5,main]) completed. Took 0.479 secs.
:processResources (Thread[Task worker for ':',5,main]) started.

> Task :processResources
Task ':processResources' is not up-to-date because:
  Output property 'destinationDir' file D:\Avans\Blok 2\Sagrada-Core\build\resources\main has been removed.
  Output property 'destinationDir' file D:\Avans\Blok 2\Sagrada-Core\build\resources\main\icons has been removed.
  Output property 'destinationDir' file D:\Avans\Blok 2\Sagrada-Core\build\resources\main\icons\arrow-right.png has been removed.
:processResources (Thread[Task worker for ':',5,main]) completed. Took 0.052 secs.
:classes (Thread[Task worker for ':',5,main]) started.

> Task :classes
Skipping task ':classes' as it has no actions.
:classes (Thread[Task worker for ':',5,main]) completed. Took 0.0 secs.
:javadoc (Thread[Task worker for ':',5,main]) started.

> Task :javadoc
Task ':javadoc' is not up-to-date because:
  Output property 'outputDirectory' file D:\Avans\Blok 2\Sagrada-Core\build\docs\javadoc has been removed.
  Output property 'outputDirectory' file D:\Avans\Blok 2\Sagrada-Core\build\docs\javadoc\Sagrada has been removed.
  Output property 'outputDirectory' file D:\Avans\Blok 2\Sagrada-Core\build\docs\javadoc\Sagrada\module-summary.html has been removed.
Starting process 'command 'C:\Program Files\Java\jdk-11.0.5\bin\javadoc.exe''. Working directory: D:\Avans\Blok 2\Sagrada-Core Command: C:\Program Files\Java\jdk-11.0.5\bin\javadoc.exe @D:\Avans\Blok 2\Sagrada-Core\build\tmp\javadoc\javadoc.options
Successfully started process 'command 'C:\Program Files\Java\jdk-11.0.5\bin\javadoc.exe''
javadoc: warning - One or more cyclic package dependencies detected: 
 - nl.avans.sagrada.controllers > nl.avans.sagrada.view.scenes > nl.avans.sagrada.controllers
 - nl.avans.sagrada.controllers > nl.avans.sagrada.view.scenes > nl.avans.sagrada.view.panes > nl.avans.sagrada.controllers
 - nl.avans.sagrada.controllers > nl.avans.sagrada.database > nl.avans.sagrada.controllers
 - nl.avans.sagrada.controllers > nl.avans.sagrada.interfaces > nl.avans.sagrada.controllers
1 warning
:javadoc (Thread[Task worker for ':',5,main]) completed. Took 5.42 secs.

BUILD SUCCESSFUL in 6s
3 actionable tasks: 3 executed
1:47:21 PM: Task execution finished 'javadoc --info'.
```


Looking at the output I think that the info on the `usage` page is either incomplete or I am not running the right `javadoc` command.

**Comment by sjoerdtalsma** [comment]
This is interesting:
```log
avadoc: warning - One or more cyclic package dependencies detected: 
 - nl.avans.sagrada.controllers > nl.avans.sagrada.view.scenes > nl.avans.sagrada.controllers
 - nl.avans.sagrada.controllers > nl.avans.sagrada.view.scenes > nl.avans.sagrada.view.panes > nl.avans.sagrada.controllers
 - nl.avans.sagrada.controllers > nl.avans.sagrada.database > nl.avans.sagrada.controllers
 - nl.avans.sagrada.controllers > nl.avans.sagrada.interfaces > nl.avans.sagrada.controllers
```

As far as I know javadoc does present this particular warning for you and is it a result of #183 that I implemented recently. Can you double-check for any `.svg` files in the javadoc output directory (I don't know where gradle writes this by default)

**Comment by sjoerdtalsma** [comment]
Any chance of showing `Sagrada-Core\build\tmp\javadoc\javadoc.options`?

**Comment by royberris** [comment]
@sjoerdtalsma ah there is a `.svg` but there was no graphics in it so I assumed it was from javadoc itself. 

It's content it saying that `Graphviz` cannot be found.

Is there an easy way I could write a (relative) output for the `.puml` file to my resources directory?

**Comment by sjoerdtalsma** [comment]
I don't know of an easy way. You need Graphviz installed to render the UML diagrams unfortunately (see #51).

You can keep the generated `.puml` files by specifying the `--createPumlFiles` doclet option, then gather them after the build. They are published alongside the sourcefiles they relate to (so `package.puml` are placed in the packages they are about, and `ClassName.puml` will be alongside `ClassName.html`). Images _can_ be moved to an images output directory, .puml not at this time.

**Comment by sjoerdtalsma** [comment]
> Is there an easy way I could write a (relative) output for the .puml file to my resources directory?

add `--createPumlFiles` doclet option and gather the .puml files from the javadoc folder in a postprocessing step?

**Comment by royberris** [comment]
@sjoerdtalsma thanks a lot for your help, I got it working. 

One more question. Right now it is showing all packages and their relation. How do I render all classes and their relation? And also the methods and attributes within the class?

**Comment by sjoerdtalsma** [comment]
Roy, those should be in the class and package diagrams?

If there is some diagram type you’re missing maybe we can add it. Pkease create a new issue with an example code and the diagram that would like to get rendered from it. 
Perhaps we can create that?

**Comment by sjoerdtalsma** [comment]
@royberris Are you okay to close this since you got it working?

I welcome further questions, bugs or feature requests as new issues.

**Comment by royberris** [comment]
@sjoerdtalsma I do have one more question.

I opened a issue on StackOverflow because I did not get it working.
And someone helped me out and showed an example of him running the tool. He got below result.

![image](https://user-images.githubusercontent.com/25608596/70059792-aea38b80-15e1-11ea-9970-0fe557de401d.png)

But when I run the UML tool like he described I only get this image: https://prnt.sc/q56os7

How do I get the same result as the image above instead of only the packages? I don't see any more SVG's generating then the one I linked in the image above.

**Comment by sjoerdtalsma** [comment]
Silly question but just in case: Did you check all subdirectories of the javadoc output?

**Comment by royberris** [comment]
@sjoerdtalsma yes I saw those but I was searching for an overview of the complete application. Where all packages are combined. But I believe now that this does not exist? If not then I will create a feature request as you mentioned above.

**Comment by sjoerdtalsma** [comment]
No worries, although it would have been civil to refer to the [stackoverflow post](https://stackoverflow.com/q/59090647/11692780) from this issue in the first place.

The diagram above is the _package diagram_ for `org.openjfx` if I interpret it correctly and you should get similar package diagrams for your own packages.

The diagram you show from your code is the _package **dependency** diagram_ that shows only the dependencies between diagrams.

If you have a project with code and an example of the diagram that would be useful to you, please create a feature request along with specifications on how to deduce the information from your code.

I may be able to generate it for you in a future version of the doclet. However, please be aware that while Javadoc provides a lot of information about your code, not everything can be deduced from it.

**Comment by sjoerdtalsma** [comment]
> an overview of the complete application. Where all packages are combined.

This would certainly be possible, however would probably result in information overload for the average java project.
