### ISSUE TITLE
Longer build time without internet connection

### ISSUE THREAD

**Issue by bmhm** [talsma-ict/umldoclet#227]
## Expected Behavior

Fast builds even with offline mode.

## Actual Behavior

Slow build times when no internet connection is available, even with offline mode.

## Steps to Reproduce the Problem

  1. Create a project, execute dependency:go-offline
  2. start a build with umldoclet with a blocking proxy

## Specifications

  - Version: any
  - Platform: any
  - Java version: any

## In depth description

As discussed in https://github.com/talsma-ict/umldoclet/issues/218#issuecomment-561029747, my build time sky rocketed on my build server. Soon I figured that the problem only occured when

 1. building on my build server
    AND
  2. umldoclet enabled.

Even `--offline` did not help, but what helped was `<detectJavaApiLink>false</detectJavaApiLink>` which suprised me. The same build without umldoclet was fast as expected.

It seems that umldoclet either swallows `isOffline` set by `--offline`, or does something on its own. With JDK14 (EA) I can see connection timeouts (SocketException) on the console.

Kindly investigate why builds with umldoclet will try to connect to the internet, while builds without umdoclet won't (or at least fail faster).
If not using umldoclet, I don't even need `--offline` -- the build will be fast anyway.

**Comment by sjoerdtalsma** [comment]
Thanks for putting in the effort to analyse the cause of this issue! :+1:

**Comment by sjoerdtalsma** [comment]
I think I found the location of the problems; the `ExternalLink` class attempts to resolve external links and I suspect it's the reason for the slow build; waiting for a response until (eventually) there's a timeout. Obviously in offline mode, this behaviour is problematic.

I have created a `develop-v2.0` branch from where I can perform a 2.0 patch release (`develop` is already preparing for the `2.1.0` milestone).

I hope to have a unit test on this new branch soon reproducing the bug so I can start a fix.

**Comment by bmhm** [comment]
Thanks, that sounds great!
I should mention, the default javadocs do not wait for a timeout even when not in offline mode.

**Comment by sjoerdtalsma** [comment]
I have removed a check for a 'live' _package-summary.html_ file to eliminate bad external links.

Could you by chance try the latest `2.0.7-SNAPSHOT` version?

In maven you may need to add the maven central snapshot repository
```xml
<repositories>
    <repository>
        <id>snapshots-repo</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases><enabled>false</enabled></releases>
        <snapshots><enabled>true</enabled></snapshots>
    </repository>
</repositories>
```

**Comment by bmhm** [comment]
I cannot use it behind my proxy :(

**Comment by sjoerdtalsma** [comment]
> I cannot use it behind my proxy :(

Oh that's too bad; I'll (try to) cut a new version then so you can declare it as a regular dependency.
Gives me a chance to test the update to my release script anyway 😉 

Please hold tight...

**Comment by bmhm** [comment]
I can test it in January :(
So no worries, no hurry.

**Comment by sjoerdtalsma** [comment]
The release script worked, just the Maven Central upload barfed.
This happens more often and that's why there is a separate CI job just for publishing the released artifacts: https://travis-ci.org/talsma-ict/umldoclet/builds/624095344

However, unfortunately for us, there seems to be a [bug in Travis](#229) that prevents us from seeing the `Restart` button on this particular job. I [reported]() it to them; let's hope it gets resolved soon so we can publish our releases again.

(in the mean time I'll see if I have enough rights to publish to maven central myself)

**Comment by sjoerdtalsma** [comment]
Ok, I managed to use the regular CI build script to actually build, sign and upload the release to Maven Central. I checked and [version `2.0.7`](https://repo1.maven.org/maven2/nl/talsmasoftware/umldoclet/2.0.7/) is already available!

**Comment by sjoerdtalsma** [comment]
@bmhm 
> I can test it in January :(
> So no worries, no hurry.

No problem; I'll leave the issue open till then. I am curious how `2.0.7` works for you though 😉

**Comment by bmhm** [comment]
A build just went through. I set the `detectApiLinks`  to `true` again and no change in build time! LGTM!

**Comment by sjoerdtalsma** [comment]
> A build just went through. I set the `detectApiLinks` to `true` again and no change in build time! LGTM! Thank you VERY much! :)

You're VERY welcome and thank you for providing the detailed analysis and being an active participant.

If there are features you would like to see in the future, please feel free to file an issue about it.
