### ISSUE TITLE
interface extends interface should be solid line

### ISSUE THREAD

**Issue by huntertran** [talsma-ict/umldoclet#245]
Hi, thanks for the work in this repo, I really appreciate it.
## Expected Behavior
Java interface extends another interface should be visualized as a solid line in UML

## Actual Behavior
dashed line

## Steps to Reproduce the Problem

  1. create a `foo` interface
  2. create `bar` interface, extends `foo`
  3. generate JavaDoc to see the dashed line

## Specifications

  - Version: 2.0.7
  - Platform: maven, windows, graviz
  - Java version: 13

resource: https://stackoverflow.com/questions/2695006/what-does-an-interface-extends-interface-relationship-look-like-in-uml

**Comment by sjoerdtalsma** [comment]
Thank you for pointing this out. The issue is now on my list of things to look into.

**Comment by sjoerdtalsma** [comment]
Fixed, I'll try to publish a new 2.0 release asap

**Comment by sjoerdtalsma** [comment]
@huntertran Release `2.0.8` has been released with the fix.
The maven-central sync could take up to a few hours.

I hope you enjoy the doclet and thanks again for pointing out this bug!
