### ISSUE TITLE
Send images to a single directory

### ISSUE THREAD

**Issue by johnWorrell** [talsma-ict/umldoclet#25]
It is difficult to embed the images (package.jpg for example) in Javadoc because they cannot be located using <img...> tags from multiple locations (the overview pages and per-package pages).

The suggested solution is to send the images to a single directory with the image files having fully package qualified names, for example org.johnWorrell.mypackage.package.jpg.

**Comment by sjoerdtalsma** [comment]
I propose the setting "umlImageDirectory" where you can provide the name of the directory to place all images.

**Comment by johnWorrell** [comment]
Great - I'll create a PR on a fork for you to review.

Cheers,

John

**Comment by sjoerdtalsma** [comment]
John, that's okay, however I also have a working version in my 'develop' branch for you to extend. If you have improvements, of course feel free to send the PR.

**Comment by johnWorrell** [comment]
Oh, well, I'll leave it to you then :-)

Are you planning to work on issue: 29 (references between classes) soon?

Thanks,

John

**Comment by sjoerdtalsma** [comment]
Reopening this issue to re-implement the feature for the 2.0.0 version.
