### ISSUE TITLE
Unanticipated error generating UML: java.lang.IllegalStateException: Cannot read from configured destination directory ""!

### ISSUE THREAD

**Issue by cradloff** [talsma-ict/umldoclet#284]
## Expected Behavior
When calling `javadoc` with UML Plugin, the documents and images should be generated.

## Actual Behavior
`javadoc` aborts with the following message:

    Constructing Javadoc information...
    UML Doclet (C) Copyright Talsma ICT, version: 2.0.10.
    This software uses PlantUML (C) Copyright Arnaud Roques, version: 1.2019.08.
    javadoc: warning - One or more cyclic package dependencies detected:
     - de.ba.operativ.leistung.kiwi.person > de.ba.operativ.leistung.kiwi.person.boundary > de.ba.operativ.leistung.kiwi.person
    Generating C:\workspace\git\person\person-business\target\apidocs\images\de.ba.operativ.leistung.kiwi.person.package.svg...
    Generating C:\workspace\git\person\person-business\target\apidocs\images\de.ba.operativ.leistung.kiwi.person.boundary.package.svg...
    
    ...
    
    Generating C:\workspace\git\person\person-business\target\apidocs\images\de.ba.operativ.leistung.kiwi.person.Main.svg...
    Generating C:\workspace\git\person\person-business\target\apidocs\images\.....................package-dependencies.svg...
    javadoc: error - Unanticipated error generating UML: java.lang.IllegalStateException: Cannot read from configured destination directory ""!
    1 error
    1 warning

## Steps to Reproduce the Problem

Call `javadoc` with the following command:

    javadoc @options @argfile

Contents of `options`:

    -classpath
    Classpath omitted for brevity
    -doclet
    'nl.talsmasoftware.umldoclet.UMLDoclet'
    -docletpath
    'C:/Users/RadloffC001/AppData/Local/Temp/MavenRepository/nl/talsmasoftware/umldoclet/2.0.10/umldoclet-2.0.10.jar'
    -encoding
    'UTF-8'
    -protected
    -sourcepath
    'C:/workspace/git/person/person-business/target/generated-sources-delombok-main'
    --uml-image-directory C:\workspace\git\person\person-business\target/apidocs/images
    -Xdoclint:none
    --delegate-doclet false

## Specifications

  - Version: 2.0.10
  - Platform: Windows 10
  - Java version: 11.0.7
  - (If open source) Project link: closed source

**Comment by sjoerdtalsma** [comment]
Thank you for reporting this bug. It looks like the options interpret absent value for directory as empty string (`""`) which obviously should not happen.

I will look into it.

**Comment by sjoerdtalsma** [comment]
Note to self: also look into the following log line:
```
Generating C:\workspace\git\person\person-business\target\apidocs\images\.....................package-dependencies.svg...
```

This also looks weird. Perhaps related to an empty destination directory?? 🤔

**Comment by cradloff** [comment]
Thanks for your reply.

Is there an option I missed to set? I didn't find a parameter for a destination directory or something similar. Or is there a workaround?

Maybe the error has something to do with the warning about the cyclic dependencies.

**Comment by sjoerdtalsma** [comment]
The standard `-d` javadoc option is for setting the directory.
That should function as a workaround for you; I still want to fix this bug though ;-)

**Comment by cradloff** [comment]
With the -d option set the error doesn't show up anymore.

Thank you very much

**Comment by joergsesterhenn** [comment]
Found our issue - we had disabled the standardDocletOptions. That's why we had to give the directory explicitly. After resetting standardDocletOptions to true everything works as expected.

**Comment by sjoerdtalsma** [comment]
Good to hear that and thank you for following up on this.
