### ISSUE TITLE
Add custom lines to generated plantuml source

### ISSUE THREAD

**Issue by fullerlee** [talsma-ict/umldoclet#292]
Hi,

Ref #51 .  Is it possible to inject custom directives into the generated plantuml?

I really want to try the jdot rendering, so need to be able to start each generated plantuml markup with `!pragma graphviz_dot jdot`

Thanks

**Comment by sjoerdtalsma** [comment]
At this moment it is not possible to write custom directives unfortunately.
It should not very complicated to add though, I'll see what I can do!

**Comment by fullerlee** [comment]
Hi @sjoerdtalsma - Do you know when 2.0.11 is planned to release to mvnrepostiory?
Thanks

**Comment by sjoerdtalsma** [comment]
I plan to release a new version this week; I want to test if some regression bugs have been fixed with the latest PlantUML version so I can upgrade the included version again.
Would that be okay or do you have an urgent need for a release _now_ ?

**Comment by fullerlee** [comment]
No, that sounds good to me.  Thanks again for your work.
