### ISSUE TITLE
Generating a Diagram Sequence

### ISSUE THREAD

**Issue by AdinhLux** [talsma-ict/umldoclet#298]
Good morning :).

First I would like to thank you for having generated and shared your project to generate automatically UML diagrams.

I decided to post this request to ask you :

a) If you will add a function to generate a Diagram Sequence in the future ?
b) If not, I would like to take the step (for learning and gaining some experience): 

> The purpose is to create a functionality [like this project](https://github.com/sherif181/java-sequence-diagram-generator) where **you're using @annotation** in Unit Tests to generate the necessary classes & methods.

**Comment by sjoerdtalsma** [comment]
Although I would love to be able to generate sequence diagrams automatically with my tool, there is one fundamental problem: The generator is a doclet.

This means it operates on the metadata collected by the Javadoc tool. Unit tests are not executed nor analysed for typical javadoc usage.

By all means, I'm open to suggestions on how to improve the tool, but based on the Javadoc metadata model I don't see how this could work.

**Comment by sjoerdtalsma** [comment]
Closing this for now, please feel free to reopen and comment if you have an idea how to establish this.
