### ISSUE TITLE
Class Diagrams generated differently when rearranging Class files into sub packages

### ISSUE THREAD

**Issue by AdinhLux** [talsma-ict/umldoclet#301]
Hello and thank you for replying to my suggestion [#298 ](https://github.com/talsma-ict/umldoclet/issues/298) As I have a little experience in Programming languages, I'm not familiar with doclets (I heard you can retrieve method calls when running or debugging, if you can confirm this point).

Anyway, let's focus on this main issue: I've created a project **containing 2 packages**: 

- 'task1' where you just compare Volume between 2 Storage objects.
- 'task2' where you define a Launcher class **instantiating a Coffee Machine  object** and you ask for different Drinks (Latte Macchiato, Hot Chocolate, Tea).

We will focus on **'task2'**.

## Diagram Class (for 'task2')
Below is a Diagram Class I've drawned:
- *Launcher.java* (contains **main** method)
- *CoffeeMachine.java* (where you ask for different Drinks : Latte Macchiato, Hot Chocolate, Tea)
- **Interfaces** : *MilkDrink.java* & *CoffeeDrink.java*
- **Abstract class** : *Drink.java* 
- **Custom Exceptions** used in  *CoffeeMachine.java* : *OutOfCoffeeException.java*,  *OutOfMilkException.java* & *OutOfTeaException.java*

<img src="https://i.imgur.com/wBy88s8.png" width="450" height="450" />

## When all Classes are in One package  (for 'task2')
> - We have a **Full View** of Package dependency diagram (the problem appears when we separate Classes into sub packages)
<img src="https://i.imgur.com/SNp58TM.png" width="425" height="225" />

> - You can notice that *CoffeeMachine.java* has **2 missing GET methods**
<img src="https://i.imgur.com/Sfg4Nvc.png" width="425" height="225" />

## When we move Classes in different packages  (for 'task2')
> - We **only** have a View of project **'task2'** of Package dependency diagram
<img src="https://i.imgur.com/wbQdn2E.png" width="425" height="225" />

> - In its Diagram Class, there are missing Classes and packages
<img src="https://i.imgur.com/6z3Xl5S.png" width="425" height="225" />

## Questions

1. Is it a minor bug ?
2. If you agree, do you have personal notes or a good documentation on : 
> how the doclet will gather and read all declared Project's methods & fields 
> how the doclet will translate the relations between these methods & fields using **plantuml**

If you need a copy of my Project to reproduce the problem, it would be with great pleasure 👍 !

**Comment by sjoerdtalsma** [comment]
> You can notice that CoffeeMachine.java has 2 missing GET methods

These are not missing, but are rendered as [JavaBean _properties_](https://docs.oracle.com/javase/tutorial/javabeans/writing/properties.html) instead. Furthermore, as they appear in the same package, they are rendered as a _uses_ relation instead (If you look closely you will see the arrow labeled with the property name).

**Comment by sjoerdtalsma** [comment]
> We only have a View of project 'task2' of Package dependency diagram

This is because there are no dependencies found from/to the other packages in your code. It is a package _dependencies_ diagram...

**Comment by sjoerdtalsma** [comment]
> In its Diagram Class, there are missing Classes and packages

Sorry to say, but your issue has become quite large and I'm not quite sure which Classes and packages you're missing from the diagram. Could you please elaborate on _what_ you're missing?

**Comment by sjoerdtalsma** [comment]
Please consider splitting this issue into multiple smaller issues, so I can address each one and not have the risk of missing any..

**Comment by AdinhLux** [comment]
> 
> 
> Please consider splitting this issue into multiple smaller issues, so I can address each one and not have the risk of missing any..

First thank you for your reply. Concerning the fact that the description of my issue is large, I will write small issues in the future.


> 
> 
> > In its Diagram Class, there are missing Classes and packages
> 
> Sorry to say, but your issue has become quite large and I'm not quite sure which Classes and packages you're missing from the diagram. Could you please elaborate on _what_ you're missing?

For my 'task2' package, I've created 2 sub packages *drink* and *exception*. I don't see my *'exception'* package and some classes are not displayed in the *'drink'* package.

![Diagram Class](https://i.imgur.com/AQs4ZAX.png)

**Comment by sjoerdtalsma** [comment]
> ... and some classes are not displayed in the 'drink' package.

What is their visibility? Have you configured Javadoc to document them?
I also don't see them in your `Class Summary` listing which isn't created by the doclet but rather by the standard javadoc.

I suspect they may be package-protected or have other non-public visibility?

**Comment by sjoerdtalsma** [comment]
> I don't see my 'exception' package ...

The `exception`  package is listed in your `Packages`  section, so should be there (including diagrams).
As I said; it probably doesn't contain package _dependencies_ so isn't listed in the _Package dependencies_ diagram for that reason.

**Comment by AdinhLux** [comment]
> 
> 
> > I don't see my 'exception' package ...
> 
> The `exception` package is listed in your `Packages` section, so should be there (including diagrams).
> As I said; it probably doesn't contain package _dependencies_ so isn't listed in the _Package dependencies_ diagram for that reason.

Yes there is a diagram here. But in my Project, my CoffeeMachine.java (in the package **lu.uni.intro2prog.exam.task2**) import these Exceptions classes (from package **lu.uni.intro2prog.exam.task2.exception**).

There should be a diagram showing the liaison between these 2 packages.

![](https://i.imgur.com/iVSYmM1.png)


I begin to understand the concept of ***Package dependencies diagram*** (I only know sequence & class diagrams).

I think, for your convenience, I should send you my little project (I have to push it to Git)

**Comment by sjoerdtalsma** [comment]
> my CoffeeMachine.java (in the package lu.uni.intro2prog.exam.task2) import these Exceptions classes

Ah yes! imports are currently not yet supported in the package dependencies diagram. Only usage of classes in the public documented API (i.e. method parameters or return types and / or field types) are currently supported.

This is also due to the limitations of the Javadoc metadata that is made available to the doclet.

I have been thinking on how I could incorporate imports into the dependency diagram, but have not yet found a way to do so.

**Comment by AdinhLux** [comment]
Thanks a lot for taking your time to read this thread. In the future, I will think about how to better summarize my Issue description.

:smile:

**Comment by sjoerdtalsma** [comment]
No worries, glad to help!
