### ISSUE TITLE
Adding thrown Exceptions to the package dependencies diagram.

### ISSUE THREAD

**Issue by AdinhLux** [talsma-ict/umldoclet#302]
Following your suggestion in this thread (#301), I've opened a separate issue for requesting to add  **thrown Exceptions to the package dependencies diagram**.

Thanks a lot for taking your time to read my previous thread. In the future, I will think about how to better summarize my Issue description.

## For the context
I've created a Project (you can find [here](https://github.com/AdinhLux/exam)) where you select a Drink at the Coffee Machine.

<img src="https://i.imgur.com/wBy88s8.png" width="650" height="450" />

## Issue when using UmlDoclet
I've created classes **extending Exception class** : `OutOfCoffeeException.java`, `OutOfTeaException.java`, `OutOfMilkException.java`.

    When using thrown Exceptions in a CoffeeMachine.java, UmlDoclet doesn't display the dependency between 2 packages: 
- **lu.uni.intro2prog.exam.task2** (who contains CoffeeMachine.java)
- **lu.uni.intro2prog.exam.task2.exception** (who contains OutOfCoffeeException.java, OutOfTeaException.java, OutOfMilkException.java)

<img src="https://i.imgur.com/6z3Xl5S.png" width="525" height="325" />

## Code showing the dependency between these 2 packages
Based on the picture below, as `CoffeeMachine.java` uses `throws OutOfCoffeeException, OutOfMilkException`, there should be a diagram showing the interaction between these 2 packages.

![](https://i.imgur.com/iVSYmM1.png)

**Comment by AdinhLux** [comment]
Hello :).

Sorry for bothering you again. But I still have the issue with your current version `2.0.11`. According to your Git page, this version is released **26 days ago** and I reported the issue 1 week ago.


I saw in your POM.xml the version is `2.0.12`:

- I can't compile it (it seems we need a licence from Redhat : com.mycila.maven.plugin.license.git.CopyrightRangeProvider)

- It seems this version is still not available in the remote repository


> When you test the features, did you use the version  `2.0.11` or  `2.0.12` ?

Thanks in advance :)

**Comment by sjoerdtalsma** [comment]
@AdinhLux `2.0.12`  has not been released yet.
You can test a pre-release _SNAPSHOT_ of it though by using the ` 2.0.12-SNAPSHOT` version (which will be updated with each build of the develop branch (until the 2.0.12 release comes out of course).

You can find snapshots on the [sonatype snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/): https://oss.sonatype.org/content/repositories/snapshots/nl/talsmasoftware/umldoclet/

If you really need it soon, I can publish a new release this week.. Just let me know

**Comment by sjoerdtalsma** [comment]
> I can't compile it (it seems we need a licence from Redhat : com.mycila.maven.plugin.license.git.CopyrightRangeProvider)

The project can be built locally with the following command:
```
./mvnw clean install
```

Please make sure you have [maven toolchains](https://maven.apache.org/guides/mini/guide-using-toolchains.html) set up with at least _both_ a JDK 8 home directory _and_ a JDK 9 (or higher) home directory, as plantuml itself can only be compiled on java 8 or less.
