### ISSUE TITLE
Upgrading spring boot service from java 8 to java 11 gives error regarding the UMLDoclet

### ISSUE THREAD

**Issue by ariafarmani** [talsma-ict/umldoclet#331]
## Bug

Within our team we try to upgrade a spring boot service from java 8 to 11 but to stumble upon a problem regarding the umldoclet. Within maven the representation module gives the following error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-uml-to-javadocs) on project representatie: MavenReportException: Error while generating Javadoc:`
`[ERROR] Exit code: 1 - javadoc: warning - The old Doclet and Taglet APIs in the packages`
`[ERROR] com.sun.javadoc, com.sun.tools.doclets and their implementations`
`[ERROR] are planned to be removed in a future JDK release. These`
`[ERROR] components have been superseded by the new APIs in jdk.javadoc.doclet.`
`[ERROR] Users are strongly recommended to migrate to the new APIs.`
`[ERROR] javadoc: error - invalid flag: -author`

#### Version

- maven-javadoc-plugin: 3.2.0
- umldoclet.version: 1.1.0

When we upgrade the UMLDoclet to a 2.x version as you've mentioned at the requirements we get the following error:

`[ERROR] Exit code: 1 - javadoc: error - invalid flag: -umlCommand`

#### Version

- maven.javadoc.plugin: 3.2.0
- umldoclet: 2.0.12

**Comment by sjoerdtalsma** [comment]
I'm confused; you state `umldoclet.version: 1.1.0` _and_ `umldoclet: 2.0.12`.

As is described in the readme, UMLDoclet version 1.x must be used up to Javadoc 8, and UMLDoclet version 2.x for Javadoc 9 (and higher).
So if you're using Javadoc version 11, please make sure you're using the latest 2.x version of the UMLDoclet.

Can you confirm exactly which version you are using?

**Comment by sjoerdtalsma** [comment]
Also, you state `maven.javadoc.plugin: 3.0.1`  while the output seems to be clearly from `maven-javadoc-plugin:3.2.0`.

**Comment by ariafarmani** [comment]
I understand the confusion. With the javadoc version 11 I am using the latest 2.x version of the UMLDoclet, but that only did not solve the issue. 

I stated both situations whereas with the first error occurs before the UMLDoclet upgrade and the second after the upgrade, but I recon that this made this more confusing. 

I copy-pasted my colleagues versionnumbers and overlooked that we were using different version. I have adjusted my first post accordingly.

**Comment by ariafarmani** [comment]
After turning off all the additional options, the error didn't occur anymore. 

These were the options:
`                                <additionalOption>-umlImageFormat SVG</additionalOption>`
`                                <additionalOption>-umlImageDirectory images</additionalOption>`
`                                <additionalOption>-umlCommand "hide empty fields"</additionalOption>`
`                                <additionalOption>-umlCommand "hide empty methods"</additionalOption>`
`                                <additionalOption>-umlExcludedReferences java.lang.Object</additionalOption>`
`                                <additionalOption>-umlExcludedReferences java.lang.Enum</additionalOption>`
`                                <additionalOption>-umlExcludedReferences java.lang.annotation.Annotation
                                </additionalOption>`
`                                <additionalOption>-umlExcludedReferences nl.talsmasoftware.reflection.dto.AbstractDto
                                </additionalOption>`

**Comment by sjoerdtalsma** [comment]
Ah I see, the error you showed unfortunately doesn't correspond to the problem of the wrong options.
Probably from when the 1.x doclet was still used?

The option `-umlCommand` was replaced by `--uml-custom-directive` in the 2.x version.
The option `-umlExcludedReferences` was renamed to `--uml-excluded-type-references`.

As described on the _Usage_ page, a list of all supported options can be obtained by running 

```
javadoc --help -docletpath umldoclet-2.x.jar -doclet nl.talsmasoftware.umldoclet.UMLDoclet
```

Or, you could take a look at the [UMLOptions.java](https://github.com/talsma-ict/umldoclet/blob/develop/src/main/java/nl/talsmasoftware/umldoclet/javadoc/UMLOptions.java) source file.

**Comment by sjoerdtalsma** [comment]
You're very welcome, glad it works now. Closing the issue.
