### ISSUE TITLE
Failure to generate UML diagrams and SVG

### ISSUE THREAD

**Issue by rockbmb** [talsma-ict/umldoclet#333]
I've browsed several issues to try and find a similar one, #160 comes close but isn't quite what I ran into.

## Expected Behavior
After running `mvn javadoc:javadoc`, appropriate `.puml` and `.svg` files are generated in a target directory, in this case `target/` (below is an example of the project structure).

```
.
├── pom.xml
├── src
│   ├── main
│   │   └── java
│   │       └── oop2021
│   │           ├── App.java
│   │           ├── --- more classes ---
|
│   └── test
│       └── java
│           └── oop2021
│               ├─ AppTest.java
|               ├── --- more classes ---
└── target
    ├── classes
    │   └── oop2021
    │       ├── App.class
    │       ├── --- more classes ---
    └── test-classes
        └── oop2021
            ├─ AppTest.class
            └── --- more classes ---
```

## Actual Behavior
None of the UML files or `.svg`s are present, and the generated documentation in `target/site/apidocs` won't have any of those either.

## Steps to Reproduce the Problem

```xml
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <version>3.0.1</version>
            <executions>
                <execution>
                    <id>attach-javadocs</id>
                    <goals>
                        <goal>jar</goal>
                    </goals>
                    <configuration>
                        <doclet>nl.talsmasoftware.umldoclet.UMLDoclet</doclet>
                        <docletArtifact>
                            <groupId>nl.talsmasoftware</groupId>
                            <artifactId>umldoclet</artifactId>
                            <version>2.0.12</version>
                        </docletArtifact>
                        <additionalOptions>
                            <!--<additionalOption>...</additionalOption>-->
                        </additionalOptions>
                    </configuration>
                </execution>
            </executions>
        </plugin>
```

  1. Create a new default Maven project.
  2. Add the snippet above to `pom.xml`, in the `<build><pluginManagement><plugins>` section, as mentioned [here](https://github.com/talsma-ict/umldoclet/blob/develop/usage.md#configuring-your-maven-build).
  3. Run `mvn javadoc:javadoc`
  4. Run `find target/ -type f -name "*.puml"` or `find target/ -type f -name "*.svg"`.
  5. The previous commands should come up empty.

## Specifications

  - Version: 2.0.12
  - Platform: Windows 10 and Ubuntu 20.04, both 64-bit.
  - Java version: JDK 16

To add: `JAVA_HOME` was properly set up in both Windows 10 and Ubuntu 20.04 when trying this, and `graphviz` is available in path (`dot(.exe) --version` works).

**Comment by sjoerdtalsma** [comment]
Have you tried your snippet in the `<build><plugins>` section as specified in the Usage page?
You mention `<build><pluginManagement>` where my usage page mentions `<build><plugins>`. This makes a difference.

- https://maven.apache.org/pom.html#Plugins
- https://maven.apache.org/pom.html#Plugin_Management

**Comment by rockbmb** [comment]
@sjoerdtalsma Thank you for the fast reply. I will do this at once and see if it works.
I must add, I'm really not well versed with Maven or Java build tools - I apologize beforehand if this has happened because of my inexperience.

**Comment by rockbmb** [comment]
I've moved the snippet to be bracketed as

```xml
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.0.1</version>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <doclet>nl.talsmasoftware.umldoclet.UMLDoclet</doclet>
              <docletArtifact>
                <groupId>nl.talsmasoftware</groupId>
                <artifactId>umldoclet</artifactId>
                <version>2.0.12</version>
              </docletArtifact>
              <additionalOptions>
                <!--<additionalOption>...</additionalOption>-->
              </additionalOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
    ...
  </build>
```

and running `mvn javadoc:javadoc` still doesn't produce any UML in `\target\site\apidocs\`, or elsewhere.
I'm using VSCode to manage the project, if that's relevant.

**Comment by sjoerdtalsma** [comment]
That's because you didn't configure the `javadoc` goal in maven but the `jar` goal of the javadoc plugin.
What happens if you run the 'standard' maven lifecycle up to _package_ (e.g. `mvn package`)?
I would expect the configuration to be applied then.

If you want it to apply to other execution phases, you could also move the `<configuration>` directly within the `<plugin>` section (so 'out' of the specific execution for building the javadoc jar file).

**Comment by sjoerdtalsma** [comment]
> I apologize beforehand if this has happened because of my inexperience.

No apologies needed, we're all still learning every single day.

**Comment by sjoerdtalsma** [comment]
I updated the _usage_ page to reflect the configuration separate from the plugin goal that was executed (such as `javadoc:javadoc` vs `javadoc:jar` as indicated in this issue)

**Comment by rockbmb** [comment]
Apologies for the late reply, I was AFK.
I'll give this a try now.

**Comment by rockbmb** [comment]
I updated my `pom.xml` with the new XML in `usage.md`, ran `mvn package`, and now I get some slick UML diagrams.

If you don't mind, I have another question: can instance variables for each class be shown on the diagrams via a doclet option, or is it not possible?

**Comment by sjoerdtalsma** [comment]
I don't understand your question. If instance variables don't show up, it's probably because they are excluded from the Javadoc documentation due to their visibility.

For more information, please see https://docs.oracle.com/javase/9/tools/javadoc.htm especially the `--show-members` option. The UMLDoclet respects those settings.

**Comment by rockbmb** [comment]
I was not aware that there were [`<additionalJOptions>`](https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#additionalJOptions), and that I could put some inside UMLDoclet's `<additionalOptions>`.
That solved my problem.

I'll close this issue now, allow me to thank you for all your help.
This is really a minor issue (that was a result of me not knowing Maven XML syntax), but you took so much time of your own to help me greatly.

Thank you very much @sjoerdtalsma!

**Comment by sjoerdtalsma** [comment]
No worries, my pleasure. And it turned out to be an opportunity to improve on my usage page 😉
