### ISSUE TITLE
Using JDK-16 package.svg graphics are not shown on package-summary pages, although graphics do get generated

### ISSUE THREAD

**Issue by juanpablo-santos** [talsma-ict/umldoclet#352]
## Expected Behavior
Being able to see package.svg generated graphics on package-summary pages when building javadocs using JDK-16

## Actual Behavior
Using JDK-16, maven-generated apidocs fail to show package.svg graphics package-summary pages, although graphics do get generated. Same project, same javadoc generation but using JDK-15 and package.svg graphics get shown again on package-summary pages.

## Steps to Reproduce the Problem

  1. maven projects using JDK-16 (either by enforcing it using toolchains or by setting appropiate `JAVA_HOME` + `PATH`env variables)
  2. mvn clean package javadoc:aggregate-no-fork -Dmaven.test.skip -U -e 
  3. package-summary classes do not show associated, generated package.svg graphics

## Specifications

  - Version: 2.0.12
  - Platform: ubuntu
  - Java version: 16
  - (If open source) Project link: N/A

**Comment by sjoerdtalsma** [comment]
Thank you for bringing this to my attention, I'll test with my OpenJDK 16 version.
