### ISSUE TITLE
Sharing a Gradle Kotlin DSL configuration

### ISSUE THREAD

**Issue by rkuijt** [talsma-ict/umldoclet#384]
The [example configuration](https://github.com/talsma-ict/umldoclet/blob/develop/usage.md#using-gradle) provided for Gradle uses the Groovy DSL.  
It took me a bit of effort to figure out the correct configuration with Kotlin DSL.
Here's the translated configuration for whoever is trying to achieve the same thing:

```kotlin
val umlDoclet: Configuration by configurations.creating

dependencies {
    umlDoclet("nl.talsmasoftware:umldoclet:2.0.15")
}

configurations {
    umlDoclet
}

tasks.javadoc {
    source = sourceSets.main.get().allJava
    val docletOptions = options as StandardJavadocDocletOptions
    docletOptions.docletpath = umlDoclet.files.toList()
    docletOptions.doclet = "nl.talsmasoftware.umldoclet.UMLDoclet"
    docletOptions.addStringOption("additionalParamName", "additionalParamValue")
}
```

**Comment by sjoerdtalsma** [comment]
Thanks a lot for this! 👍 

I will add it to the examples when I find some time. 
However, I'd also be honored to accept this contribution in a pull request if you feel inclined to do so.

**Comment by rkuijt** [comment]
Late reply, unfortunately I wasn't able to find the time earlier. Thanks for the PR/merge!
