### ISSUE TITLE
Dot Executable: null on windows when GRAPHVIZ_DOT not declared

### ISSUE THREAD

**Issue by razibus** [talsma-ict/umldoclet#398]
## Expected Behavior
With a valid all users Graphviz installation on Windows, running `mvn javadoc:jar` with `nl.talsmasoftware.umldoclet.UMLDoclet`configured in pom.xml should produce the class diagrams in all the generated pages. 

## Actual Behavior
With a valid all users Graphviz installation on Windows, running `mvn javadoc:jar` with `nl.talsmasoftware.umldoclet.UMLDoclet`configured in pom.xml does not produce the class diagrams in all the pages where a class is linked to another class. Then the following message is shown in place of the image:

```
Dot Executable: null
No dot executable found
Cannot find Graphviz. You should try
@startuml
testdot
@enduml
or
java -jar plantuml.jar -testdot
```

When the class is standalone, its image is correctly generated. 

## Steps to Reproduce the Problem

  1. unpack included project on a windows system with java 11 and maven 3.2.0 and graphviz installed
  2. verify that GRAPHVIZ_DOT variable is not set
  3. in the project root, using a terminal, launch `mvn clean package`
  4. after successful build, open target/apidocs/index.html in a browser
 
If you reproduce those steps with GRAPHVIZ_DOT correctly set with the dot.exe file path, you will get the images correctly built. 

Please note that the 2.0.16-SNAPSHOT version of the UMLDoclet on the develop branch does not build on windows systems due to incorrect file separator and linux-style end of line usage. Check with `mvn clean package` on a git pulled version from develop branch on a Windows system. This produces errors like:
```
[ERROR]   DiagramTest.testCustomDirective:124 
Expected: iterable containing ["@startuml", "!pragma graphviz_dot jdot", "", "center footer UMLDoclet 2.0.16-SNAPSHOT, PlantUML 1.2022.1", "@enduml"]
     but: item 0: was "@startuml\r"
[ERROR]   FileUtilsTest.testRelativePath:52 
Expected: is "subdir1/testfile.adoc"
     but: was "subdir1\\testfile.adoc"
```

## Specifications

  - Version: UMLDoclet 2.0.15, PlantUML 1.2021.13
  - Platform: Windows 10 pro 21H1
  - Java version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9
  - (If open source) Project link: 
[rule21.zip](https://github.com/talsma-ict/umldoclet/files/8244261/rule21.zip)

**Comment by sjoerdtalsma** [comment]
Thanks for reporting this. I'll look into it. However, I have very limited time and troubleshooting this involves getting a trial Windows version running in a virtual machine on a Mac M1 chip, so please be patient with me 😉 ...

**Comment by razibus** [comment]
Ok Sjoerd, if I find some spare time I may also contribute. 
Where are you located ? I live in France. 
Regards

Alain

----- Mail original -----
De: "Sjoerd Talsma" ***@***.***>
À: "talsma-ict/umldoclet" ***@***.***>
Cc: "Alain Touret" ***@***.***>, "Author" ***@***.***>
Envoyé: Lundi 14 Mars 2022 19:56:33
Objet: Re: [talsma-ict/umldoclet] Dot Executable: null on windows when GRAPHVIZ_DOT not declared (Issue #398)





Thanks for reporting this. I'll look into it. However, I have very limited time and troubleshooting this involves getting a trial Windows version running in a virtual machine on a Mac M1 chip, so please be patient with me 😉 ... 

— 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .

**Comment by sjoerdtalsma** [comment]
Alain, thanks for your offer.
I'm located in The Netherlands. If you could contribute that would be awesome!

Ideally I would love to just use the existing Apache-licensed PlantUML jar, but as I cannot download it with maven, I have to build from sources instead, which is rather cumbersome to be honest!

**Comment by razibus** [comment]
Ok
I have looked at the errors. 
Many tests are checking results that are system specific. The idea is to make them system-agnostic. 
When you write data into a file, the line separator looks to be also system-specific. Do you think this should be normalized, say choose to use \n or \r\n on any system ? Does PlantUml tolerate any of them ?
I effectively saw that the plant uml version used by the docklet is an old version. Do you have other reason than the licence to not include the latest version ?

Regards

----- Mail original -----
De: "Sjoerd Talsma" ***@***.***>
À: "talsma-ict/umldoclet" ***@***.***>
Cc: "Alain Touret" ***@***.***>, "Author" ***@***.***>
Envoyé: Mardi 15 Mars 2022 11:00:51
Objet: Re: [talsma-ict/umldoclet] Dot Executable: null on windows when GRAPHVIZ_DOT not declared (Issue #398)





Alain, thanks for your offer. 
I'm located in The Netherlands. If you could contribute that would be awesome! 

Ideally I would love to just use the existing Apache-licensed PlantUML jar, but as I cannot download it with maven, I have to build from sources instead, which is rather cumbersome to be honest! 

— 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .

**Comment by sjoerdtalsma** [comment]
I found a few platform-dependent `\n` uses and made them platform-independent (see #399)

**Comment by sjoerdtalsma** [comment]
> I effectively saw that the plant uml version used by the docklet is an old version. Do you have other reason than the licence to not include the latest version ?

No reason other than that it is boring work to download and unzip the sources into the appropriate folder and check whether the entire build still works. Also, there is very little benefit to using the latest and greates version, as the generated diagrams are as simple as possible to remain as compatible as we can.

**Comment by sjoerdtalsma** [comment]
The PlantUML version was bumped and I have found no more system-specific newlines in the Doclet sources.
Closing this issue for now. In the readme it is documented that Graphviz should be installed, so I won't really put much effort into getting that to work; this could probably be fixed better if a non-GPL version of PlantUML could be used as a regular maven dependency.
