### ISSUE TITLE
Typo in usage example for gradle integration.

### ISSUE THREAD

**Issue by nimmzwei** [talsma-ict/umldoclet#40]
...
options.doclet**P**ath = configurations.umlDoclet.files.asType(List)
...

For the doclet to be found by gradle,
the correct setting must be a small letter "p" as in "options.doclet**p**ath".
Source:
https://docs.gradle.org/3.5.1/javadoc/org/gradle/external/javadoc/MinimalJavadocOptions.html#docletpath(java.io.File...)

**Comment by sjoerdtalsma** [comment]
Thanks @nimmzwei  I corrected the typo.
Could you take a look at #41 whether I understood your issue correctly?

**Comment by nimmzwei** [comment]
#41 should fix it.
thanks for this great doclet.

**Comment by sjoerdtalsma** [comment]
Glad you like it 😃.
Struggling with Java 9 at the moment; looks like it will require mostly a full re-build to support it fully, so your appreciation helps my motivation.
