### ISSUE TITLE
Is there a way to backport the styling from v2 to v1?

### ISSUE THREAD

**Issue by spyhunter99** [talsma-ict/umldoclet#448]
**Is your feature request related to a problem? Please describe.**  
I did a test run of the latest v2.x of this doclet and I love the output, exactly what i'm looking for. Unfortunately, (at least temporarily) I'm running on a jdk8 project. When using the older 1.x version, the output, while still nice, has a very different look and feel. I much prefer the v2 theming, fonts, colors, etc. 

**Describe the solution you'd like**  
Is there a way to override the theming or perhaps even backport the styling from v2 to the v1.x branch?

**Describe alternatives you've considered**  
I did try recompiling the 2.x branch for java 8. Didn't go so well. Doclet apis seem significantly different

**Additional context**

**Comment by sjoerdtalsma** [comment]
The styling is 100% down to the PlantUML version being used.
I _could_ try upgrading the dependenciesof the v1 doclet and see if I can issue a new release from it...

Recompiling the new code won't work as indeed the Doclet spec was changed from Javadoc 9 onwards and the code was completely rewritten to incoroporate the new Doclet spec.

**Comment by spyhunter99** [comment]
I did try your suggestion and was able to get it to work!

- update the PlantUML version to the latest
- add commons-io as a dependency
- edit the HtmlFile class to use the commons-io FileUtils to copy instead of the current api call to `net.sourceforge.plantuml.FileUtils` which now requires an `SFile` class. Wasn't sure what that was but the logic seemed simple enough to use commons-io as a replacement.

I did have one issue the license plugin so i temporarily disabled it. I can open a PR if you have any hints as to the license plugin issue. It was complaining about the HtmlFile class that i edited and the root pom xml file. Is there some goal i need to run to update the license headers?

**Comment by sjoerdtalsma** [comment]
The `develop-v1` branch hasn't been updated in a while so the copyright years can be off for many files you touch.
Commons IO cannot be added as a dependency unfortunately; everything should be bundled into the `.jar` file or else running javadoc will be a much more complex process.

You can fix this by running a `mvn license:format` before you commit.
Also please make sure you sign off your commits (using the git commit `-s` option) or the Pull request cannot be accepted.

Thanks very much in advance.

**Comment by sjoerdtalsma** [comment]
Update: PlantUML ASL version `1.2022.14` should now be available in the local mvn repo of the `develop-v1` branch if you pull the recent version.

**Comment by sjoerdtalsma** [comment]
I did a quick inline of a `copy(File, File)` method and bumped some other lib versions.
I'll see if I can push out a release in a while. Until then, the latest `1.1.5-SNAPSHOT` from https://oss.sonatype.org/content/repositories/snapshots should be updated with the latest PlantUML version.

**Comment by sjoerdtalsma** [comment]
Sorry, the github actions build for the `develop-v1` branch seems to be broken, so no snaphot or release are available on maven central yet. 😢 

For now you could check out the branch and do a `mvn install` locally to install the doclet in your local maven repository for testing.

I'll see if I can fix the build in the meantime.. Sorry for the inconvenience..

**Comment by sjoerdtalsma** [comment]
Ok, fixed it and pushed a release to maven central.
Please try version `1.1.5` of umldoclet.
Feel free to reopen this issue if it hasn't been resolved still somehow.

**Comment by sjoerdtalsma** [comment]
Oh, I almost forgot; check out https://www.javadoc.io/doc/nl.talsmasoftware/umldoclet/1.1.5/index.html for an example

**Comment by spyhunter99** [comment]
excellent, thank you!

**Comment by nicola02nb** [comment]
Hi, I was using v 1.1.4 without any problem, and I saw your update to 1.1.5, but as I'll try the update it gives me a lot warnings while compilig javadoc and some graphs don't display... can you help me?

**Comment by sjoerdtalsma** [comment]
Java 8 is already 9 years old, we will not be putting much effort in the 1.x version anymore.
However, if you have a reproducable bug, please feel free to create a new issue for them.

**Comment by nicola02nb** [comment]
Fine, I switched to 2.1, I don't want to cause any trouble... But if you want i can provide errors log
