### ISSUE TITLE
How to add PlantUML to the classpath

### ISSUE THREAD

**Issue by Weltraumschaf** [talsma-ict/umldoclet#48]
Could you please extend the documentation on how to add PlantUML to the Maven config, so that SVG will be rendered automatically. I've tried:

```xml
<plugin>
    <artifactId>maven-javadoc-plugin</artifactId>

    <dependencies>
        <dependency>
            <groupId>net.sourceforge.plantuml</groupId>
            <artifactId>plantuml</artifactId>
            <version>1.2017.18</version>
        </dependency>
    </dependencies>

    <executions>
        <execution>
            <id>attach-javadocs</id>

            <goals>
                <goal>javadoc</goal>
                <goal>jar</goal>
            </goals>

            <configuration>
                <doclet>nl.talsmasoftware.umldoclet.UMLDoclet</doclet>
                <docletArtifact>
                    <groupId>nl.talsmasoftware</groupId>
                    <artifactId>umldoclet</artifactId>
                    <version>1.0.13</version>
                </docletArtifact>
                <additionalparam>
                    -umlImageFormat SVG
                </additionalparam>
            </configuration>
        </execution>
    </executions>
</plugin>
```

But the logoutput of umldoclet says there is no PlantUML on the classpath

**Comment by Weltraumschaf** [comment]
I also tried it like described here: https://maven.apache.org/plugins/maven-javadoc-plugin/examples/additional-dependencies.html

Neither in plugin `<configuration>` nor in executions `<configuration>` works.

**Comment by sjoerdtalsma** [comment]
Which version of the JavaDoc maven plugin do you use?
I noticed the same phenomenon with `3.0.0-M1`, while `2.10.4` worked fine.

I'm currently working on a full rewrite for JDK9. I'll make sure to test with the latest maven-javadoc-plugin version.

**Comment by sjoerdtalsma** [comment]
For the moment I downgrade the javadoc plugin myself:
https://github.com/talsma-ict/reflection/commit/86f01c2617116d47b21a43db8428b8b255e54898

**Comment by fooloomanzoo** [comment]
How would you add PlantUML to the classpath in **gradle** so that rendering could work?

**Comment by sjoerdtalsma** [comment]
> How would you add PlantUML to the classpath in gradle so that rendering could work?

I don't use gradle myself very often, so I'm not quite sure about that.
Maven stopped working with the upgrade from the `maven-javadoc-plugin` to `3.0.0-M1`.
Did gradle stop working also recently?

**Comment by sjoerdtalsma** [comment]
It might be an option to actually bundle a recent PlantUML version with the doclet itself.
It has advantages and disadvantages (less control), however the doclet won't 'automatically' support new plantuml features out-of-the-box anyway, so bundling it may not even be so bad.
IANAL so not really sure whether bundling is allowed, will have to read the plantuml license for that.

**Comment by fooloomanzoo** [comment]
It does generate puml-Files, but setting a fileFormat has no effects. I tried to compile from the PlantUML Maven Files:
`
dependencies {
    compile group: 'net.sourceforge.plantuml', name: 'plantuml', version: '8059'
    umlDoclet "nl.talsmasoftware:umldoclet:1.0.13"
}
`
and it didn't work but I'm not experienced enough with gradle to say what went wrong.

**Comment by sjoerdtalsma** [comment]
I think I can bundle PlantUML in the doclet, but not the version published on maven central as that has the GPL license where this doclet is under the less-restrictive Apache license.
Fortunately, there's an [ASL version of plantuml](http://plantuml.com/download#asl) as well.
Unfortunately it's unavailable as a maven download, but I think I can tweak my build to include it without much trouble...

Seeing that plantuml isn't a java9 bundle yet either, that may actually be a good way to go for the moment.

**Comment by sjoerdtalsma** [comment]
Testing with the SNAPSHOT version from #50 seems to _work_ with the `maven-javadoc-plugin` version `3.0.0-M1` (with previously failed).
I have no doubt that this version will also work with gradle.

I'll print out some copyright messages that we're using plantuml internally and will release a `1.0.14` version this weekend.

Is that okay @Weltraumschaf and @fooloomanzoo ?

**Comment by sjoerdtalsma** [comment]
Release `1.0.14` is available: https://repo1.maven.org/maven2/nl/talsmasoftware/umldoclet/1.0.14/

**Comment by Weltraumschaf** [comment]
Sorry for not responding. Yes, I use `maven-javadoc-plugin` version `3.0.0-M1`. I'll try it out :-)
