### ISSUE TITLE
Allow provide additional plantUML options(rendern with Smetana)

### ISSUE THREAD

**Issue by Ciruman** [talsma-ict/umldoclet#480]
**Is your feature request related to a problem? Please describe.**  
The generation of the diagrams has a dependency to [Graphviz/DOT](https://plantuml.com/graphviz-dot) which in some scenarios is not easy/comfortable to provide(build pipelines)

**Describe the solution you'd like**  
It is possible to provide additional plantuml options like the following:

```
<additionalOptions>
     <additionalOption>-createWithSmetana</additionalOption>
</additionalOptions>
```
which means:
`!pragma layout smetana`
or
`java -jar plantuml.jar -Playout=smetana`

**Describe alternatives you've considered**  
It could be an option in the additionalOptions sections but It could be better if any PlantUML option could be provided because it will be more flexible and will allow to generate the diagrams with different templates:
`!theme carbon-gray`
or
`java -jar plantuml.jar -theme carbon-gray`
[More information](https://plantuml.com/command-line#6a26f548831e6a8c)

Something like this:
```
<plantumlOptions>-theme carbon-gray -Playout=smetana</plantumlOptions>
```
or
```
<additionalOptions>
     <additionalOption>-plantUmlOptions -theme carbon-gray -Playout=smetana</additionalOption>
</additionalOptions>
```

**Comment by sjoerdtalsma** [comment]
I think what you want is already possible with the current version of UMLDoclet:

1. It is possible to run without dot executable if you specify a plantuml server location with the `--plantuml-server-url` option.
2. You can specify custom PlantUML directives using the `--uml-custom-directive` option.

e.g. 
```xml
<additionalOptions>
    <additionalOption>--uml-custom-directive !pragma layout smetana</additionalOption>
</additionalOptions>
```

**Comment by Ciruman** [comment]
I think the proposed solution 2 does not work. With the following options:

```
                    <additionalOptions>
                        <additionalOption>--uml-custom-directive !pragma layout smetana</additionalOption>
                    </additionalOptions>
```

```
                    <additionalOptions>
                        <additionalOption>--uml-custom-directive !theme vibrant</additionalOption>
                    </additionalOptions>
```


If I try this I get the following errors:


```
Exit code: 2
error: No source files for package layout
1 error
Command line was: [...]/java/17.0.4.1-tem/bin/javadoc @options @packages

Refer to the generated Javadoc files in '[...]/target/apidocs' dir.
```


```
Exit code: 2
error: No source files for package vibrant
1 error
Command line was: [...]/java/17.0.4.1-tem/bin/javadoc @options @packages

Refer to the generated Javadoc files in '[...]/target/apidocs' dir.
```

**Comment by Ciruman** [comment]
@sjoerdtalsma, would you like to answer here the error I commented or would you like a new bug ticket?

**Comment by sjoerdtalsma** [comment]
That has got to do with the way the javadoc tool interprets the commandline options. 
I did have previous success with these options. If I can make some time, I will experiment with some quotes around the expression so it gets interpreted as a single string value.
