### ISSUE TITLE
Built-in graphviz alternative

### ISSUE THREAD

**Issue by sjoerdtalsma** [talsma-ict/umldoclet#51]
Since we already bundle PlantUML with the doclet, including a few extra libraries may not be so bad to reach an all-in-one solution without depending on graphviz.

A working solution is described here:
- http://plantuml.com/vizjs

It may be possible to include this in the Java 9 (v2.0) doclet rewrite.

**Comment by sjoerdtalsma** [comment]
We _could_ perform a rudimentary test for Graphviz availability (e.g. check for the `GRAPHVIZ_DOT` environment variable) and if it is not available, fall back on `jdot` by adding the following pragma to the diagrams:
```
!pragma graphviz_dot jdot
```

This may be low-hanging fruit, as `jdot` is pre-bundled with plantuml

**Comment by sjoerdtalsma** [comment]
Positioning looks ok, but arrows are still broken:
![image](https://user-images.githubusercontent.com/2930348/48823560-927bd600-ed61-11e8-8c85-1253ef54f4a8.png)

**Comment by huffstler** [comment]
PlantUML might have already gotten the work done for you on this issue 👀

https://plantuml.com/smetana02
https://github.com/plantuml/plantuml/discussions/1346

**Comment by sjoerdtalsma** [comment]
Thanks for the heads-up @huffstler , it looks like the diagrams created with UMLDoclet are _nearly_ there.
Only the footer gets rendered wrong still, but possibly I can find a way to work around that.

Would be great if we could run without hamcrest with the all-in-one jar. 👍
