### ISSUE TITLE
Enable "-link" option multiple times

### ISSUE THREAD

**Issue by erickjx** [talsma-ict/umldoclet#513]
Hi, can enable "-link" option multiple times to include different sites? it only accept 1

**Comment by sjoerdtalsma** [comment]
Closing this for now. 

Multiple links seem to work fine in my [Context Propagation library](https://github.com/talsma-ict/context-propagation) here: [example](https://github.com/talsma-ict/context-propagation/blob/51745fde53d5305fa53399af22f91566663e3108/pom.xml#L235)

Feel free to reopen this issue or submit another one if you can provide details for a failing use-case.
