### ISSUE TITLE
Configure Built-In plantuml to not steal keyboard focus on MacOS X

### ISSUE THREAD

**Issue by arthurvl** [talsma-ict/umldoclet#547]
**Is your feature request related to a problem? Please describe.**  
Running a JavaDoc with UMLDoclet from maven repeatedly steals keyboard focus on MacOS X. This makes it hard to use the computer while the javadoc generation is running.

**Describe the solution you'd like**  
It would be good to provide a mechanism to set the java.awt.headless=true property for the run context of the built-in plantuml, or do so by default.

**Describe alternatives you've considered**  
Setting java.awt.headless through _JAVA_OPTIONS works but is somewhat clunky. Neither JAVA_OPTS nor MAVEN_OPTS will be picked up. Setting it through additionalJOptions or additionalOptions also does not work. Having to set it at all can now only be documented in a readme or faq, rather than set in e.g. the pom.xml.

**Comment by sjoerdtalsma** [comment]
Perhaps the maven javadoc plugin could (/should) set this system property by default?
I can't imagine any usecase for running anything non-headless from the javadoc plugin.

**Comment by sjoerdtalsma** [comment]
>Results in: Headless? java.awt.headless=true, GraphicsEnvironment.isHeadless()=false

Okay, that _may_ have been a bit premature running tests from my IDE 🫣.

Commandline maven gives me:
```log
[INFO] --- maven-javadoc-plugin:3.6.3:jar (attach-javadocs) @ umldoclet ---
[INFO] No previous run data found, generating javadoc.
[INFO] 
Headless? java.awt.headless=true, GraphicsEnvironment.isHeadless()=true
```

I'll create a version where I set the `java.awt.headless` system property _directly_ when loading the doclet class (first 'contact' UMLDoclet gets). It won't hurt and _might_ even fix the issue. 🤞

**Comment by sjoerdtalsma** [comment]
Closing this issue to lack of activity. @arthurvl feel free to re-open if you still experience this issue with the latest version.
