### ISSUE TITLE
Feature request: ability to influence the style of generated diagrams.

### ISSUE THREAD

**Issue by hboer1965** [talsma-ict/umldoclet#6]
Hi,

I'd like to see the functionality added for influencing _style changes_ to generated diagram.
For instance, a way to add "hide class circle" to the generated puml.

For the _how_ of this request: If one could supply an "!include directive" to some location to this doclet, that would do the trick, I think.

Thanks in advance!

Kind regards,

Herman de Boer.

**Comment by sjoerdtalsma** [comment]
Great idea!

My initial strategy would be to add yet another configuration option for the 'default behaviour' for all packages and classes.
Furthermore, some kind of javadoc tag should be added to allow per-_package_, _class_, _method_ or _field_ overrides in style.

**Comment by sjoerdtalsma** [comment]
The choice of javadoc tags to use should **not** be taken lightly..
They form the 'public api' of this doclet and should therefore ideally be supported forever.
