### ISSUE TITLE
No dot executable found

### ISSUE THREAD

**Issue by wytten** [talsma-ict/umldoclet#65]
I must be doing something wrong...In order to activate the doclet, I had to remove the execution from the suggested pom.xml configuration.  Then after running 'mvn javadoc:javadoc', the generated PNG files contain the message "No dot executable found", but I have confirmed that dot.exe is in my PATH.  What am I missing?

`        <plugin>`
`            <groupId>org.apache.maven.plugins</groupId>`
`            <artifactId>maven-javadoc-plugin</artifactId>`
`            <version>3.0.0</version>`
`            <configuration>`
`                <doclet>nl.talsmasoftware.umldoclet.UMLDoclet</doclet>`
`                <docletArtifact>`
`                    <groupId>nl.talsmasoftware</groupId>`
`                    <artifactId>umldoclet</artifactId>`
`                    <version>1.0.17</version>`
`                </docletArtifact>`
`                <additionalOptions>`
`                    <additionalOption>-umlLogLevel DEBUG</additionalOption>`
`                    <additionalOption>-umlImageFormat PNG</additionalOption>`
`                </additionalOptions>`
`            </configuration>`
`        </plugin>`

**Comment by sjoerdtalsma** [comment]
This problem is caused by the way [plantuml](http://plantuml.com) uses graphviz.
Obviously, it would not have occurred with a pure-java graphviz alternative (see #51).
