### ISSUE TITLE
Re-implement links for 2.0.0

### ISSUE THREAD

**Issue by sjoerdtalsma** [talsma-ict/umldoclet#69]
The feature means adding links to the class javadoc (html page) from the generated images, i.e. the class and package diagrams. This way, when you click a class on a complex package diagram, you get sent to its JavaDoc page directly.

**Comment by sratatata** [comment]
Could you provide a little more description here?

**Comment by sjoerdtalsma** [comment]
@sratatata 
>Could you provide a little more description here?

Yes, sorry I didn't realize this would be rather cryptic for others 😉 
The feature means adding links to the class javadoc (html page) from the generated images, i.e. the class and package diagrams. This way, when you click a class on a complex package diagram, you get sent to its JavaDoc page directly.
This used to work in the `1.x` version but hasn't been built into the `2.x` rewrite yet.
This issue is so I don't forget to.
